spring.application.name=MovieRecommendationPlatform

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/movie_db

spring.data.mongodb.database=movie_db

jwt.secret=MovieRecommendationPlatformSecretKeyForJwtAuthentication2026@123456789ABCDEF
 
 cloudinary.cloud-name=dab8d76qd
cloudinary.api-key=458349215475835
cloudinary.api-secret=9FWnzUMhw8ifQJ-OAa4nzzUiJiY